### ISSUE TITLE
Добавить страницу "Основное меню"

### ISSUE THREAD

**Issue by johnnyshut** [Axioma-OneS/agro-grain-south#17]
**Вид:**

![image](https://user-images.githubusercontent.com/42472223/116850140-c1682880-abf8-11eb-944f-6c15f334d3b0.png)

**Реквизиты/объекты:**

- [x] Показать инструкцию//Скрыть  инструкцию - При нажатии на ссылку – показывается или скрывается инструкция

![image](https://user-images.githubusercontent.com/42472223/116850204-e492d800-abf8-11eb-9178-29da1c1ddbe7.png)

- [x] Контрагенты - При нажатии на ссылку Контрагенты осуществляется переход на лист «Реестр контрагентов»
- [x] Контрагенты  + - При нажатии на кнопку + Осуществляется переход на лист «Контрагент»
- [x] Договоры - При нажатии на ссылку Контрагенты осуществляется   переход на лист «Реестр договоров»
- [x] Договоры   + - При нажатии на кнопку    +   Осуществляется переход на лист «Договор»
- [x] Спецификации   + - При нажатии на кнопку    +   Осуществляется переход на лист «Спецификация»
- [x] Перевозки   + - При нажатии на кнопку    +   Осуществляется переход на лист «Перевозка»
- [x] Доп. услуги (очистка, фасовка и пр.)   + - При нажатии на кнопку    +   Осуществляется переход на лист «Доп. услуги»
- [x] Фильтр   Скрыть завершенные сделки - да - При Истинном значении фильтра скрываются все   завершённые сделки. Значение по умолчанию - истина
- [x] Фильтр   Поставщик продукции - Отбор по элементу справочника Контрагенты и типу   взаимоотношений «Поставщик продукции»
- [x] Фильтр   Вид продукции - Отбор по элементу справочника Номенклатура

**Отчетная форма**

- [x] Поставщик - Элемент справочника Контрагенты (Поставщики).   Разворачивается при нажатии на строку или спецсимвол « > ». Разворачивается до аналитики – Вид продукции и производимой по ней Сделке. При раскрытии одной из Сделок (строки   данного реестра) сворачивается развернутая ранее, то есть одновременно одна   раскрыта либо все свернуты.
- [x] Вид продукции - Элемент справочника Номенклатура из Спецификации   с Поставщиком
- [x] Номер заключающего документа (спецификация или договор) - Реквизит документа Спецификация – «номер   документа». Если договор без спецификации[Д5] , то выводится номер договора
- [x] Объем продукции по сделке, т - Реквизит документа Спецификация – «Количество»
- [x] Вывезенный объем, т - Расчетный реквизит    Вывезенный объем, т = Вывезенный объем = Сумма   весов Отгрузок EXW (Сумма   Объем отгрузки, т по всем документам Отгрузка от поставщика, введенных на   основании данной Спецификации) + Сумма весов Поступлений CPT (Сумма всех Объем поступления, т   по документам Поступление товаров на склад, введенных на основании данной   Спецификации)   (Поступления CPT – это Поступления товаров на склад,   которые не подвязаны к Отгрузкам от поставщика через поле аналитика,   Доставка поставщика = Да)
- [x] Поступивший на склад объем, т - Сумма всех Объем поступления, т по документам   Поступление товаров на склад, введенных на основании данной Спецификации
- [x] "Дата окончания спецификации   или окончания отгрузки по договору" - Реквизит документа Спецификация - «Дата окончания спецификации»
- [ ] Сделка завершена? - Значения: Нет или Да . Указываются вручную в таблице.   Нет -  при   условии, что статус документа Спецификация отличен от Закрыт   Да – при условии, что статус документа   Спецификация - Закрыт   Если сделка завершена, то Спецификацию /   расширенный договор нельзя указывать в подчиненных формах (Перевозка,   Доп.услуги)
- [x] Статус - Данный столбец недоступен для редактирования   пользователем, значение устанавливается автоматически   Цвет значения по умолчанию – Нет цвета   Цвет значения – действует – при условии – Реквизит   документа Спецификация «Дата окончания спецификации» минус 7 дней[Д1] [k2]  (диапазон проверяемых дат отклонения: от   7 дней до окончания до Дата окончания спецификации включительно)   Цвет значения – просрочена – при условии – Статус документа   Спецификация не равно Закрыт И Реквизит документа Спецификация «Дата   окончания спецификации» меньше текущей даты   Цвет значения – завершена – при условии – Статус документа   Спецификация  равно Закрыт
- [x] Перевозка по сделке   Дата отгрузки - Список реквизитов документов Отгрузка от   поставщика – Дата отгрузки,   введенных на основании Спецификации или договора
- [x] Перевозка по сделке   Номер ТТН/ЖДН - Список реквизитов документов Отгрузка от   поставщика – Номер ТТН ЖДН,   введенных на основании Спецификации или договора
- [x] Перевозка по сделке   Номер ТС - Список реквизитов документов Отгрузка от   поставщика – Транспорт – Гос номер,   введенных на основании Спецификации или договора
- [x] Перевозка по сделке   Объем отгрузки, т - Список реквизитов документов Отгрузка от   поставщика – Вес,   введенных на основании Спецификации или договора
- [x] Добавить отгрузку EXW - Кнопка «добавить отгрузку EXW +» осуществляет   переход на лист «Перевозка»   с автоматически выставленным   базисом  и спецификацией, в группировке которой   находится.
- [x] Перевозка по сделке   Объем поступления, т - Список реквизитов документов Поступление товаров   на склад – Количество,    введенных на основании документа Спецификация
- [x] Перевозка по сделке   Дата поступления - Список реквизитов документов Поступление товаров   на склад – Дата поступления,    Введенных на основании документа Спецификация
- [x] Завершить доставку EXW - Кнопка «завершить доставку EXW +»   При нажатии на кнопку производится смена статуса   документа Отгрузка от поставщика на Закрыт   Кнопка появляется в строке по документу Отгрузка   от поставщика, отличному от Закрыт       Если пользователь нажал   1. завершить доставку EXW, то открывается редактирование полей прямо   в таблице,   При нажатии клавиши ввод или клика на стороннюю область и при условии   полного заполнения                  - автоматически   дополняется и сохраняется соответствующая Форма Перевозка    При неполном заполнении форма дает объявление "Внесите   недостающие данные"
- [x] Добавить поступление CPT - Кнопка «добавить поступление CPT +» осуществляется переход на лист [Д1] [k2] [Д3] [ЕМ4] «Перевозка» с автоматически   выставленным базисом   При нажатии на кнопку становятся доступными полями   для заполнения:   Объем поступления   Дата поступления   Склад поступления   Типы полей для заполнения выделены желтым цветом.     
                                       
![image](https://user-images.githubusercontent.com/42472223/116862886-19f5f080-ac0e-11eb-9b0f-e5edc5252050.png)
                                                  
На основании внесенных данных и Спецификации в   фоновом режиме создается документ Поступление товаров на склад. В документ   «поступления» реквизиты переносятся из Спецификации. Активируется Поле ввода,   в которое вносится «объем поступления, т» - число, точность 3, которое   записывается в реквизит – Количество. Документ проводится.

- [x] Перевозка по сделке   Склад поступления - Список реквизитов документов Поступление товаров   на склад – Склад,    Введенных на основании документа Отгрузка от   поставщика по Спецификации или договору
- [x] Перевозка по сделке   Статус - Если статус документа Отгрузка от поставщика – В   пути, то статус устанавливается - В пути,    Если статус документа Отгрузка от поставщика –   Доставлено, то статус устанавливается - Доставлено   Если реквизит ТЧ Товары документа Поступление   товаров на склад – Доставка – ДА НЕТ , то Статус изначально - Доставлено
- [x] Доп.услуги по сделке:   Поставщик услуги - Реквизит Поставщик услуги документа Заявка на   услуги, введенного на основании Спецификации
- [x] Добавить доп.услугу - Кнопка «добавить доп.услугу +». При нажатии   осуществляется переход на лист «Доп.услуги»
- [x] Доп.услуги по сделке:   Описание услуги - Реквизит Описание услуги документа Заявка на   услуги, введенного на основании Спецификации
- [x] Доп.услуги по сделке:   Номер заключающего документа - Реквизит Номер документа Заявка на услуги,   введенного на основании Спецификации
- [x] Доп.услуги по сделке:   Дата заключения - Реквизит Дата заключения документа Заявка на   услуги, введенного на основании Спецификации
- [x] Доп.услуги по сделке:   Крайний срок исполнения услуги - Реквизит Крайний срок исполнения услуги документа   Заявка на услуги, введенного на основании Спецификации
- [x] Доп.услуги по сделке:   Услуга оказана? - Отмечается пользователем прямо в данной таблице. Перечисление   Да/Нет
- [x] Доп.услуги по сделке:   Статус - Статус документа Заявка на услуги. При указании   реквизита «Услуга оказана? – да» устанавливается статус Завершена. По   умолчанию – В работе.

**Доработка конфигурации:**

Доработки конфигурации отсутствуют

**Комментарии:**

- [x] Завершить сделку, удалить договор, спецификацию, перевозку или доп.услугу можно только с согласия Коммерческого директора. Создать роль «Коммерческий директор» и производить проверку на наличие роли у текущего пользователя.
- [x] Дополнительное условие для удаления спецификации: согласование удаления не начинается, если у спецификации есть подчиненные Перевозка или Доп.услуга.
- [x] Если у пользователя отсутствует роль на завершение/удаление, то выдается сообщение о необходимости согласования действия с КД:
- [x] «Согласовать <действие> по  <объект> Да Нет»
- [x] При выборе варианта –Нет – форма закрывается, никаких действий не совершается.
- [x] При выборе варианта – Да – отправляется задача пользователю с ролью «Согласующий коммерческие условия закупок» со ссылкой на объект изменения

![image](https://user-images.githubusercontent.com/42472223/116863064-63ded680-ac0e-11eb-9883-7b3abd395c7a.png)

- [x] Использовать типовой функционал Задание и типовую роль адресации - Согласующий коммерческие условия закупок. Пользователи, согласующие за роль Согласующий коммерческие условия закупок устанавливаются НСИ и администрирование – Закупки – Ответственные за согласование коммерческих условия 
- [x] Задача на согласование действий придет в виде

![image](https://user-images.githubusercontent.com/42472223/116863095-70632f00-ac0e-11eb-84f3-6c6cbcf6cdba.png)

- [x] От пользователя требуется нажатие кнопки:
- [x] Выполнено, при согласовании действий с объектом
- [x] Отменено – указание причины отмены согласования
- [x] При нажатии – Выполнено, активируется возможность у текущего пользователя действие над объектом.

[АРМ Закупка.docx](https://github.com/Axioma-OneS/agro-grain-south/files/6414126/default.docx)

**Comment by johnnyshut** [comment]
Перенес кнопки в табличной части в нормальные места. 
Изменил поведение кнопки "Создать поступление CPT" - появляется, если не было поступлений, сначала заполняем оранжевые поля в строке, потом в этой же строке нажимаем "Создать поступление CPT", после чего создается документ.

**Comment by johnnyshut** [comment]
Задача на коммерческого директора создается, но изменил логику: требуется из задачи перейти в предмет и пометить на удаление

**Comment by johnnyshut** [comment]
@Antkryloff забирай

**Comment by Antkryloff** [comment]
Если в отчете применен отбор по Поставщику или культуре, то исчезают строки с документами перевозки
![2021-05-16_16-45-12](https://user-images.githubusercontent.com/59701926/118399602-93f29480-b666-11eb-901c-4409b4f92a93.png)
![2021-05-16_16-45-41](https://user-images.githubusercontent.com/59701926/118399603-948b2b00-b666-11eb-841a-f4131638ea64.png)
