### ISSUE TITLE
Правки страницы "Спецификация"

### ISSUE THREAD

**Issue by johnnyshut** [Axioma-OneS/agro-grain-south#2]
1.	В Городе выводить выпадающий список только с теми городами, которые использовались в наших Складах.
2.	Убрать строку Ед. изм., вместо нее справа от числового значения Объема разместить надпись «тонны», выделить красным шрифтом
3.	Создать возможность клика в пустое место на форме. Активное в данный момент поле должно перейти в состояние, как если кликнуть на другое поле. Если поле подразумевало авторасчеты в других полях, то авторасчеты должны тоже быть произведены.
4.	При повторном нажатии на кнопку Изменить снова блокировать форму. То есть переключатель с двумя позициями.
5.	Сделать обязательным прикрепление хотя бы одного файла к документу, создаваемому на форме.
6.	Отображать в прикрепленных файлах название прикрепленного документа с гиперссылкой с возможностью скачать ранее прикрепленный файл.
7.	Сейчас АРМ открывается не на полный экран, при дальнейшей реализации планируется открывать АРМ без меню слева, сверху и тд, например, как на скрине. Просьба подтвердить, как будет выглядеть.
8.	В основном меню изменить структуру:

"**Перейти к**
Реестр контрагентов
Реестр договоров

**Создать новый**
Контрагент
Договор
Спецификация
Перевозка
Доп. услуги"

9.	Базисы поставки в Спецификации переименовать на EXW и CPT. CPT = Поставщик (на наш склад).
10.	Переименовать поле «Объем товара т.» -> 
«Объем товара (по спецификации) [поле ввода] тонны»
«Цена товара с НДС» -> «Цена товара с НДС (по спецификации, за 1 тонну)»
11.	Из перечня Ставка НДС товара оставить варианты: 20, 10, 0 
12.	После «Сумма: [поле ввода]» разместить надпись «руб.»
13.	Минимизировать ширину списка по возможности. Например, 

«Дата окончания спецификации (по документу)» 

разбить на две строки:

«Дата окончания спецификации
(по документу)»

14.	Перед кнопкой Изменить разместить надпись «Изменить [кнопка]».

**Comment by johnnyshut** [comment]
3 пункт реализовать нельзя

**Comment by johnnyshut** [comment]
@Antkryloff отправил доработки по последним правкам. 
Попробуй самостоятельно клонировать репозиторий на компьютер и получить cf из исходников. (Скрипт "010-prepare-dev.cmd", cf файл создастся в каталоге "build/ib")

**Comment by Antkryloff** [comment]
Замечания к работе с вложением:
- На скриншотах при попытке открыть файл выдает ошибку
- Наименование файла в поле не кликабельно
Пожелание - сделать так чтобы открывалось только окно АРМ у пользователя для тестов с ролью, потому как теперь при работе с несколькими окнами также отображается отдельное окно 1С. Если это трудоемко - вывести в дальнейшую разработку.
![2021-03-30_11-19-26](https://user-images.githubusercontent.com/59701926/112958379-15d83e00-914b-11eb-88de-3d0def13291a.png)
![2021-03-30_11-20-00](https://user-images.githubusercontent.com/59701926/112958382-1670d480-914b-11eb-8dfa-8f98387f7e29.png)

**Comment by johnnyshut** [comment]
@Antkryloff 
1. Обнови у клиента платформу до 1С:Предприятие 8.3 (8.3.18.1289);
2. Все кликабельно, если там файл один, то естественно он как был выделен так и остается, двойной клик по нему не работает, нужно выбелить файл и нажать "Сохранить файл";
3. Обработка АРМ Закупки открывается поверх 1С и блокирует все остальное, не возможно переключиться на задний фон или еще что-то, АРМ нельзя даже свернуть. 

НИКАКИХ правок не вносил.
