### ISSUE TITLE
Добавить страницу "Реестр контрагентов"

### ISSUE THREAD

**Issue by johnnyshut** [Axioma-OneS/agro-grain-south#7]
**Вид:**

- [x] ![image](https://user-images.githubusercontent.com/42472223/113521232-ce194280-95a0-11eb-8029-242bf9f294c6.png)

**Реквизиты/объекты:**

- [x] Вернуться в основное меню - Гиперссылка. При нажатии происходит переход на лист   обработки «основное меню»;
- [x] Фильтр - Два типа отборов: 1. Отбор по организационно-правовой форме контрагента (Юрлицо, Физлицо и тд). 2. Отбор по реквизитам юридического адреса контрагента;
- [x] Создать нового контрагента - По кнопке «+» осуществляется переход на лист «Контрагент»;
- [x] Поиск - Осуществляется поиск и переход по строке в «таблице» контрагентов; 
![image](https://user-images.githubusercontent.com/42472223/113521286-36682400-95a1-11eb-8c77-68470e3a8fee.png)
- [x] Категория контрагента - Выводятся контрагенты с группировкой по реквизиту «тип взаимоотношений» элемента справочника контрагенты с возможностью раскрытия группировки;
- [x] Наименование - Сокращенное наименование элемента справочника контрагенты;
- [x] Почта - Электронная почта элемента справочника контрагенты;
- [x] Номер телефона - Телефон элемента справочника контрагенты;
- [x] Юридический адрес - Юридический адрес элемента справочника контрагенты;
- [x] Создать договор с контрагентом - По кнопке «+» осуществляется переход на лист «Договор»;
- [x] Уже есть 1 или более договор - «Да» - при наличии договора с контрагентом   соответствующей группы, то есть, при наличии контрагента в группе «поставщики   продукции» проверяется наличие договора с реквизитом «поставщики продукции».   «Нет» - отсутствие договора соответствующего типа.

**Доработка конфигурации:**

Доработки типовых объектов конфигурации отсутствуют

**Комментарии:**

- [x] Пользователь видит только своих контрагентов, но если дублирует по ИНН, пытаясь создать, то контрагент появляется для него, введенные в изначальную форму данные в этом случае не записываются. 
- [x] При попытке ввести на карточке контрагента дублирующий ИНН система сразу сообщает о наличии такого контрагента, чтобы пользователь не заполнял всю форму.
- [x] Категории контрагентов свернуты по умолчанию, но их можно развернуть до контрагентов.
- [x] Категории контрагентов зависят от реквизитов «Тип взаимоотношений» элемента справочника Контрагенты, если у контрагента еще не установлен тип взаимоотношений, то элемент попадает в категорию «Без категории». Если у контрагента отмечено несколько «типов взаимоотношений», то он отображается в каждой категории. Таким образом, при отсутствии договора, контрагент находится в категории – Без категории, но при появлении договора, уже в этой группе не отображается.  Контрагентов находится в реестре хотя бы в одной из категорий.

[АРМ_Закупка_v3.docx](https://github.com/Axioma-OneS/agro-grain-south/files/6255336/_._v3.docx)

**Comment by johnnyshut** [comment]
@Antkryloff отправил доработки.

1. _"2. Отбор по реквизитам юридического адреса контрагента"_ - Убрал, так как в поле поиск тот же функционал;
2. _"Пользователь видит только своих контрагентов, но если дублирует по ИНН, пытаясь создать, то контрагент появляется для него, введенные в изначальную форму данные в этом случае не записываются."_ - После загрузки cf, нужно запустить обработку из каталога **"\libs \epfs \ДополнительнаяОбработка_Заполнить_РС_ОтветственныеМенеджерыПартнеров.epf"**.

**Comment by Antkryloff** [comment]
Просьба исправить наименование столбца на форме Реестр контрагентов с "Есть договора" на "Есть договоры"
![2021-04-08_15-29-51](https://user-images.githubusercontent.com/59701926/114027588-3194c000-9880-11eb-8baa-d92698268ee1.png)

**Comment by johnnyshut** [comment]
@Antkryloff Исправил, отправлю в следующем потоке. Этот ишуз закрываю.
