### ISSUE TITLE
Добавить страницу "Договор"

### ISSUE THREAD

**Issue by johnnyshut** [Axioma-OneS/agro-grain-south#9]
**Вид:**

![image](https://user-images.githubusercontent.com/42472223/113982345-5160bf80-9851-11eb-9a43-83cd8501f19a.png)

**Реквизиты/объекты:**

- [x] Вернуться в основное меню - Гиперссылка. При нажатии происходит переход на   лист обработки «основное меню». При наличии не сохраненных данных на форме   выдается сообщение ""Данные не сохранены и будут удалены после выхода. Продолжить?" Да/Остаться"
- [x] Изменить - Кнопка. Первичное состояние видимости – не   отображается на форме. Появляется при сохранении данных на форме. Нажатие на   кнопку «изменить» активирует возможность изменения реквизитов формы.
- [x] Контрагент - Отбор из справочника Контрагенты
- [x] По кнопке «+» - Осуществляется переход на лист «Контрагент»
- [x] Тип договора - Выбор типа договора: Поставка продукции, Перевозка, Доп.услуги, Хранение. Реквизит – Булево. Устанавливается в истинное значение вручную напротив одного из значений. Установить можно несколько значений. Записывается в реквизит элемента справочника Договор контрагента – Тип договора (дорабатываемый реквизит)
- [x] Договор № - Строка. Заполняется вручную. Записывается в реквизит элемента справочника "Договор контрагента – Номер договора"
- [x] Дата заключения - Дата, Формат – ДД.ММ.ГГГГ. Заполняется вручную. Записывается в реквизит элемента справочника "Договор контрагента – Дата договора"
- [x] Договор действует с - Дата, Формат – ДД.ММ.ГГГГ. Заполняется вручную. Записывается в реквизит элемента справочника "Договор контрагента – Дата начала действия договора"
- [x] по - 3 варианта окончания действия договора: - до полного исполнения (реквизит Булево) - бессрочный (реквизит Булево) - дата, Формат – ДД.ММ.ГГГГ. Заполняется вручную. Записывается в реквизит элемента справочника Договор контрагента – Дата окончания действия договора
- [x] Договор не подразумевает спецификацию - Реквизит Булево

**Договор не подразумевает спецификацию - Если ИСТИНА. Тип договора = Поставка продукции. При заполнении реквизитов формы создается документ Спецификация:**

- [x] Базис поставки - Выбор из перечисления Способ доставки документа Спецификация + «не указано в договоре»
- [x] Дата окончания отгрузки - Дата, формат – ДД.ММ.ГГГГ. Записывается в   реквизит документа Спецификация – дата окончания спецификации
- [x] Логистика – Тип перевозки  Перечисление «тип перевозки» документа   Спецификация
- [x] Адрес выгрузки - Город - Поле ввода - строка
- [x] Адрес выгрузки – Склад грузополучателя - Элемент справочника «Склады и магазины». На   основании заполненного реквизита формы «город» произвести отбор по реквизиту   элемента справочника «Склады и магазины» - Адрес склада – Город. Список   выбора должен быть ограничен перечнем складов по городу
- [x] Условия спецификации на товар – Вид продукции - Реквизит выбора элемента справочника   «Номенклатура». Реализовать способ выбора – по наименованию и отбором   напрямую из формы справочника.
- [x] Условия спецификации на товар – Объем товара,т - Поле ввода – число, точность 2
- [x] Условия спецификации на товар – Ед. изм - Ссылка на справочник Упаковки (единицы   измерения). Автоматически заполняется элементом – тонна. Реквизит не   редактируется.
- [x] Условия спецификации на товар – Цена товара с НДС - Поле ввода – число, точность 2
- [x] Условия спецификации на товар – Сумма - Поле ввода – число, точность 2. Автоматически   рассчитывается как   объем товара * Цена товара с НДС
- [x] Условия спецификации на товар – Ставка НДС товара - Перечисление. Ставка НДС. Автоматически   заполняется из реквизита элемента справочника Номенклатура ставка НДС из   реквизита формы – «Вид продукции»
- [x] Условия спецификации на товар – Сумма НДС - Поле ввода – число, точность 2. Автоматически   рассчитывается   Сумма НДС = Сумма без НДС * Ставка НДС/100   Сумма без НДС зависит от реквизита вхождения НДС

**Договор не подразумевает спецификацию = ИСТИНА. Тип договора = Допуслуги/хранение. При заполнении реквизитов формы создается документ Заказ на допуслуги:**

- [x] Описание услуги - Выбор типа реквизита: Строка или Перечисление.   При выборе строки, разрешить произвольное   заполнение услуги.   При выборе типа перечисления, производится выбор   из списка: Фасовка, Очистка, Мешки или перевозка мешков, Агентские услуги, Карантинные сертификаты, Этикетки, Хранение. Значение реквизиты записывается документ "Заявка на доп. услуги – реквизит Услуги".
- [x] Крайний срок исполнения услуги - Дата, формат ДД.ММ.ГГГГ – реквизит документа   Заявка на доп. услуги
- [x] Условия спецификации на услугу – Стоимость с НДС - Реквизит – Число, точность 2 знака. Вводится   вручную
- [x] Условия спецификации на услугу – Ставка НДС - Реквизит – перечисление Ставка НДС. Выбирается   вручную
- [x] Условия спецификации на услугу – НДС - Расчетный реквизит = Стоимость с НДС*Ставка   НДС/100
- [x] В рамках спецификации на товар - Выбор документа спецификации по контрагенту

**Продолжение основной формы для всех типов договор:**

- [ ] Прикрепить файл - Функционал приложенных файлов
- [x] Комментарий - Поле ввода - Строка
- [x] Сохранить - Кнопка. При нажатии кнопки происходит запись   документа спецификация. После нажатия кнопки сохранить, реквизиты формы   блокируются, открываются к редактированию только после нажатия кнопки "Изменить". Если сохранен договор с истинным реквизитом «  Договор не подразумевает спецификацию»
- [x] Сохранить и вернуться в основное меню - Кнопка. При нажатии на кнопку происходит   сохранение информации в документ спецификация и происходит переход на лист   «основное меню»
- [x] Сохранить и перейти к созданию спецификация - Кнопка. При нажатии на кнопку происходит   сохранение информации в документ спецификация и происходит переход на лист «спецификация».   Кнопка отсутствует, если установлен реквизит «Договор не подразумевает   спецификацию»
- [x] Удалить и закрыть - Кнопка появляется только после нажатия кнопки   Изменить. При нажатии кнопки, внесенная информация очищается и форма закрывается.

**Доработка конфигурации:**

- [x] Требуется доработка типа договора с контрагентом

![image](https://user-images.githubusercontent.com/42472223/113991514-3430ee80-985b-11eb-82d8-7e05a8199e17.png)

- [x] Реквизиты типа Булево. Устанавливается вручную. При создании нового договора, в связанном элементе справочника Контрагенты выставляется соответствующий реквизит «Тип взаимоотношений». 
- [x] Варианты окончания действия договора контрагента:  до полного исполнения – реквизит Булево; бессрочный – реквизит Булево.
- [x] Договор не подразумевает спецификацию – реквизит Булево. По умолчанию видимость – ложь, появляется при всех типах договора, кроме типа договора – Перевозка.

**Комментарии:**

- [x] При сохранении данных формы создается новый элемент справочника Договоры контрагентов.
- [x] Все реквизиты – обязательны для заполнения, принимая во внимание условия.

[АРМ_Закупка_v5.docx](https://github.com/Axioma-OneS/agro-grain-south/files/6277113/_._v5.docx)

**Comment by johnnyshut** [comment]
"Базис поставки - Выбор из перечисления Способ доставки документа Спецификация + «не указано в договоре»"
 - Противоречит логике, так как у нас нет такого базиса. 

"Прикрепить файл - Функционал приложенных файлов"
 - противоречит логике, так как спецификацию без прикрепленных файлов провести нельзя и у нас уже есть прикрепленные файлы у спецификации

"Сохранить и перейти к созданию спецификация - Кнопка. При нажатии на кнопку происходит сохранение информации в документ спецификация и происходит переход на лист «спецификация». Кнопка отсутствует, если установлен реквизит «Договор не подразумевает спецификацию»" 
- противоречит логике, так как мы в этой странице создаем спецификацию

**Comment by johnnyshut** [comment]
@Antkryloff забирай страницу "Договор"

**Comment by Antkryloff** [comment]
Обратная связь от заказчика
[АРМ_Закупка_v10 Приемка Договора и Реестра.docx](https://github.com/Axioma-OneS/agro-grain-south/files/6344895/_._v10.docx)
